### ISSUE TITLE
the problem about webservice test

### ISSUE THREAD

**Issue by xiongsd** [mohorev/yii2-soap-server#3]
when i test webservice in yii2 it happens below error,

```
Fatal error: Uncaught SoapFault exception: [SOAP-ENV:Client]
Bad Request in C:\wamp\www\1.php:3
Stack trace:
    #0 C:\wamp\www\1.php(3): SoapClient->__call('getHello', Array)
    #1 C:\wamp\www\1.php(3): SoapClient->getHello('fsd')
    #2 {main} thrown in C:\wamp\www\1.php on line 3
```

servercode：

``` php
<?php

namespace app\controllers;

use yii\base\Controller;

class ApiController extends Controller
{
    public function actions()
    {
        return [
            'hello' => [
                'class' => 'mongosoft\soapserver\Action',
            ],
        ];
    }

    /**
     * @param string $name Your name
     * @return string
     * @soap
     */
    public function getHello($name)
    {
        return 'Hello ' . $name;
    }
}
```

clientcode:

``` php
<?php
    $client = new SoapClient('http://localhost/webservice/web/index.php?r=api/hello');
    print_r($client->getHello("fsd"));
```

i am sorry ,i am poor in english , but i want to solve the problem, who can help me?tell why?

**Comment by mohorev** [comment]
ApiController controller should extend from [[yii\web\Controller]] or its child classes.

**Comment by ahmadzaenalm** [comment]
how to generate wsdl?
